version: '3.7'

services:
  nuxt:
    build: ./frontend/
    container_name: nuxt-container
    restart: always
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:1.13
    container_name: nginx-container
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    depends_on:
      - nuxt

  nest:
    container_name: nest-container
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
      - '5431:5431'
      - '9229:9229'
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb

  postgresdb:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    name: webnet

volumes:
  mongo_data:
