name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          password: ${{secrets.PASSWORD}}
          username: root
          port: 22
          script: |
            cd /home/volsu-schedule
            git pull origin master
            docker-compose -f docker-compose.prod.yml up --build -V -d
            docker ps -a
