name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: connect to ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_PRIVATE}}
          username: root
          port: 22
          scipt: |
            cd /home/volsu-schedule
            git pull origin master
            docker-compose up --build -V
